"""PR merge -> Issue status rollup.

Called by .github/workflows/pr-close-issues.yml after a PR is merged.
Parses closed Issue numbers from the PR body, applies status: verified
to FR/NFR/IF Issues, rolls up to parent UNs when all siblings verify,
and closes the stage Milestone when all of its UNs verify.

This is the **sole writer** of `status: verified` and `status: validated`.
Other agents post evidence comments via github_comment.py but must not
move labels — see METHODOLOGY.md §1.

Configuration:
  requirements/requirement-map.yml  — UN -> FR/NFR/IF/KPM decomposition,
                                      stage -> UN mapping
  config/stages.yml                  — milestone definitions (canonical
                                      titles also live on GitHub Milestones;
                                      this script parses live titles)
  dev-docs/github-issue-map.json    — optional cached Issue lookup;
                                      regenerated by seed_github.py
"""
import argparse
import json
import os
import re
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).parent.parent))
from scripts.github_client import GitHubClient

REPO_ROOT = Path(__file__).parent.parent
ISSUE_MAP_PATH = REPO_ROOT / "dev-docs" / "github-issue-map.json"
REQ_MAP_PATH = REPO_ROOT / "requirements" / "requirement-map.yml"


def load_maps() -> tuple[dict, dict]:
    issue_map = json.loads(ISSUE_MAP_PATH.read_text()) if ISSUE_MAP_PATH.exists() else {}
    req_map = yaml.safe_load(REQ_MAP_PATH.read_text()) if REQ_MAP_PATH.exists() else {"stages": {}, "user_needs": {}}
    return issue_map, req_map


def build_reverse_maps(issue_map: dict, req_map: dict) -> tuple[dict, dict]:
    """Return (req_to_uns, un_to_stage).

    A single FR/NFR/IF may legitimately decompose more than one UN.
    `req_to_uns` therefore returns *all* parent UNs for each requirement,
    not just the last one written.
    """
    req_to_uns: dict[str, list[str]] = {}
    un_to_stage: dict[str, int] = {}

    for stage_num, stage_data in req_map.get("stages", {}).items():
        for un_id in stage_data.get("user_needs", []):
            un_to_stage[un_id] = stage_num
            un_entry = req_map.get("user_needs", {}).get(un_id, {})
            for child_field in (
                "functional_requirements",
                "non_functional_requirements",
                "interface_requirements",
            ):
                for child_id in un_entry.get(child_field, []) or []:
                    req_to_uns.setdefault(child_id, []).append(un_id)

    return req_to_uns, un_to_stage


def build_num_to_req_id(issue_map: dict) -> dict[int, str]:
    """Map GitHub Issue number -> requirement ID for all FR/NFR/IF entries."""
    result: dict[int, str] = {}
    for section in ("functional_requirements", "non_functional_requirements", "interface_requirements"):
        for req_id, data in issue_map.get(section, {}).items():
            result[data["number"]] = req_id
    return result


def is_verified(issue: dict) -> bool:
    return any(l["name"] == "status: verified" for l in issue.get("labels", []))


def get_req_issue_num(issue_map: dict, req_id: str) -> int | None:
    for section in ("functional_requirements", "non_functional_requirements", "interface_requirements"):
        entry = issue_map.get(section, {}).get(req_id)
        if entry:
            return entry["number"]
    return None


def build_stage_to_milestone(client: GitHubClient) -> dict[int, int]:
    """Map stage number -> milestone number by parsing milestone titles.

    Titles must start with "Stage N" (e.g. "Stage 4 — Host Integration").
    A stage without a matching milestone logs a warning and is skipped
    for closure purposes.
    """
    result: dict[int, int] = {}
    pattern = re.compile(r"^Stage\s+(\d+)\b")
    for ms in client.list_milestones(state="all"):
        m = pattern.match(ms.get("title", ""))
        if m:
            result[int(m.group(1))] = ms["number"]
    return result


def rollup(pr_body: str, dry_run: bool = False) -> None:
    issue_map, req_map = load_maps()
    req_to_uns, un_to_stage = build_reverse_maps(issue_map, req_map)
    num_to_req_id = build_num_to_req_id(issue_map)

    client = GitHubClient()
    stage_to_milestone_num = build_stage_to_milestone(client)

    # Fetch all issues once to avoid repeated list API calls
    all_issues_list = client.list_issues(state="all")
    all_issues: dict[int, dict] = {i["number"]: i for i in all_issues_list}

    closed_nums = [
        int(m)
        for m in re.findall(r"(?:Closes|Fixes|Resolves)\s+#(\d+)", pr_body, re.IGNORECASE)
    ]
    print(f"Closed issue numbers from PR body: {closed_nums}")

    newly_verified_uns: set[str] = set()

    for num in closed_nums:
        req_id = num_to_req_id.get(num)
        if not req_id:
            print(f"  #{num}: not a tracked FR/NFR/IF — skipping")
            continue

        print(f"  #{num} ({req_id}): applying status: verified")
        if not dry_run:
            client.replace_status_label(num, "status: verified")
        # Update local cache so sibling checks see this as verified
        if num in all_issues:
            labels = [l for l in all_issues[num].get("labels", []) if not l["name"].startswith("status:")]
            labels.append({"name": "status: verified"})
            all_issues[num]["labels"] = labels

        parent_uns = req_to_uns.get(req_id, [])
        if not parent_uns:
            print(f"    no parent UN for {req_id} — skipping rollup")
            continue

        for parent_un in parent_uns:
            # Check all FR/NFR/IF siblings under this parent
            un_entry = req_map.get("user_needs", {}).get(parent_un, {})
            sibling_ids = (
                (un_entry.get("functional_requirements") or []) +
                (un_entry.get("non_functional_requirements") or []) +
                (un_entry.get("interface_requirements") or [])
            )

            unverified = []
            for sib_id in sibling_ids:
                sib_num = get_req_issue_num(issue_map, sib_id)
                if not sib_num:
                    continue
                sib_issue = all_issues.get(sib_num, {})
                if not is_verified(sib_issue):
                    unverified.append(f"{sib_id} (#{sib_num})")

            if unverified:
                print(f"    {parent_un}: siblings not yet verified: {', '.join(unverified)}")
                continue

            un_num = issue_map.get("user_needs", {}).get(parent_un, {}).get("number")
            if not un_num:
                # Fall back to live lookup when the map isn't seeded
                from scripts.github_client import GitHubClient as _GC  # type: ignore
                found = client.find_issue_by_title(f"[{parent_un}]")
                if found:
                    un_num = found["number"]
            if not un_num:
                continue
            if parent_un in newly_verified_uns:
                # Already promoted via another sibling FR in this same PR
                continue
            print(f"    all siblings verified -> {parent_un} (#{un_num}): applying status: verified")
            if not dry_run:
                client.replace_status_label(un_num, "status: verified")
            if un_num in all_issues:
                labels = [l for l in all_issues[un_num].get("labels", []) if not l["name"].startswith("status:")]
                labels.append({"name": "status: verified"})
                all_issues[un_num]["labels"] = labels
            newly_verified_uns.add(parent_un)

    # Stage rollup — close the Milestone when all its UNs verify.
    closed_stages: set[int] = set()
    for un_id in newly_verified_uns:
        stage_num = un_to_stage.get(un_id)
        if stage_num is None or stage_num in closed_stages:
            continue

        stage_data = req_map.get("stages", {}).get(stage_num, {})
        all_uns_in_stage = stage_data.get("user_needs", [])

        unverified_uns = []
        for un in all_uns_in_stage:
            un_num = issue_map.get("user_needs", {}).get(un, {}).get("number")
            if not un_num:
                continue
            un_issue = all_issues.get(un_num, {})
            if not is_verified(un_issue):
                unverified_uns.append(f"{un} (#{un_num})")

        if unverified_uns:
            print(f"  Stage {stage_num}: UNs not yet verified: {', '.join(unverified_uns)}")
            continue

        milestone_num = stage_to_milestone_num.get(stage_num)
        if milestone_num:
            print(f"  Stage {stage_num}: all UNs verified -> closing Milestone #{milestone_num}")
            if not dry_run:
                client.close_milestone(milestone_num)
            closed_stages.add(stage_num)
        else:
            print(f"  Stage {stage_num}: all UNs verified but no matching Milestone found "
                  f"(title must start with 'Stage {stage_num}'). Skipping closure.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Roll up PR Issue status after merge")
    parser.add_argument("--dry-run", action="store_true", help="Print planned actions without touching GitHub")
    args = parser.parse_args()

    pr_body = os.environ.get("PR_BODY", "")
    if not pr_body:
        print("PR_BODY env var is empty — nothing to process")
        sys.exit(0)

    rollup(pr_body, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
